<!DOCTYPE html>
<html>
<head>
    <style >
        ul{
    margin:1em;
}
    </style>
	<title>Philequity Corner (December 24, 2012)</title>
    	   <link href="styles.css" rel="stylesheet">
        <div align="justify" class="page">
    	
                <br><br><br><br><h3><b><font style="verdana">Philequity Corner (December 24, 2012)<br>By Valentino Sy</font></b></td></h3>
</div>

        
        <p align="center"><b>Christmas Presents</b></p>
        <p>2012 has been a good year for global stocks as most major global indices have delivered double-digit year-to-date (YTD) returns. In a year where most major global stock indexes have done quite well, the PSE Index has delivered a stellar YTD return of 33.2% and has been one of the best performing stock markets in the world for 2012. Since we normally open presents on Christmas Eve and Christmas Day, we find it appropriate to count our blessings and enumerate the gifts that the Philippine stock market has received for the year 2012.</p>

        <p align="center"><b>15 Gifts of Christmas</b></p>
        <p><b>1. Ben Bernanke.</b>&nbsp;We consider Fed Chairman Ben Bernanke the Santa Claus of the global market. Bernanke has repeatedly used quantitative easing (QE), which refers to unconventional monetary policy tools employed by central banks when conventional monetary policies have started to become ineffective. With creative policy moves such as Operation Twist (<i>The Twist,</i> September 26, 2011) and QE Infinity (<i>The Great Global Monetary Easing,</i> October 22, 2012), Bernanke’s actions have so far contributed to the improving outlook for the US economy and the US housing market. More importantly, his policies have become a model for other global central banks to follow.</p>
        <p><b>2. Mario Draghi.</b>&nbsp;Like his American counterpart, ECB President Mario Draghi made a bold move when he said that “the ECB is ready to do whatever it takes to preserve the euro” (<i>Whatever It Takes,</i> August 27, 2012). Draghi delivered on his promise by introducing Outright Monetary Transactions (OMT), a program which calls for unlimited purchases of government bonds of troubled European countries that apply to the program. The institution of OMT has significantly calmed the bond markets of indebted European countries such as Spain and Italy.</p>
        <p><b>3. European leaders.</b>&nbsp;The European leaders have made significant progress in containing the European sovereign debt crisis. Their determination to preserve Greece’s EU membership has led to a credit rating upgrade of Greece from S&P. Moreover, the agreement of EU leaders to establish a European banking supervisor is considered a breakthrough towards stabilizing and strengthening the region’s banking system (<i>Italy Defeats Germany,</i> July 2, 2012).</p>
        <p><b>4. Global central banks.</b>&nbsp;Following the examples of Bernanke and Draghi, the central banks of Brazil, Australia, China, Russia and India also lowered their respective benchmark interest rates. This appears to be a coordinated effort from global central banks to ease monetary conditions, lift asset prices and stimulate their respective economies (<i>Central Banks Winning, </i>September 17, 2012).</p>
        <p><b>5. S&P, Fitch and Moody’s credit rating upgrades.</b>&nbsp;In the past few years, rating agencies have repeatedly upgraded the credit rating of the Philippines because of the country’s strong economic and fiscal performance. As such, the country is only one notch below investment grade based on the ratings of the three major credit rating agencies. We believe that it is only a matter of time before the Philippines is classified as investment grade. This impending upgrade will further boost the weighting of Philippine stocks in international equity portfolios.</p>

        <p><b>6. PNoy.</b>&nbsp;The trust and confidence that is bestowed upon the Aquino administration emanates from the top – from President Noynoy Aquino himself – and flows to the Cabinet. This has translated to confidence in the local stock market and Philippine assets in general (<i>SONA in Tables and Graphs,</i> July 30, 2012). The administration has stayed true to its mandate of promoting good governance and improving the country’s fiscal position. Moreover, PNoy is not beholden or indebted to any specific parties or sectors, allowing him to successfully pursue and pass bold reforms such as the Sin Tax and Reproductive Health (RH) Bills. Lastly, the administration has forged a peace agreement with the Moro Islamic Liberation Front (MILF), paving the way for the influx of investments in the Mindanao area.</p>
        <p><b>7. Congress.</b>&nbsp;The Senate and the House of Representatives played important roles in passing the Sin Tax and RH Bills into law. The passage of sin taxes is a clear sign that the government is fiscally responsible. The RH Bill, on the other hand, will significantly contribute to a healthier and more educated populace. These bills stayed in the pipelines for more than a decade and we admire our Congress for having the will and resolve to finally approve these bills into law. Both foreign and local investors lauded the passage of these bills as positive for the country’s economy.</p>
        <p><b>8. Department of Finance (DOF) and the country’s economic managers.</b>&nbsp;Led by DOF Secretary Cesar Purisima, our country’s economic managers have done an excellent job of rationalizing government expenses while increasing government revenues. Preliminary estimates show that the collection of the Bureau of Internal Revenues (BIR) may have reached the P1T mark for the year. Moreover, it is important to note that the government has maintained a very strong fiscal position while ushering in strong economic growth. While the 7.1% 3Q2012 GDP growth was a welcome surprise, many economists believe that sustaining the country’s GDP growth within the 5-6% band will translate to more inclusive economic growth.</p>
        <p><b>9. Bangko Sentral ng Pilipinas (BSP).</b>&nbsp;Under the leadership of BSP Governor Amando Tetangco, Jr., BSP has come up with the appropriate policy responses amidst an ever-changing global economy. Like most global central banks, BSP lowered its benchmark interest rates four times in 2012 in order to keep domestic consumption buoyant amidst weak global demand. Moreover, BSP has played an important role in cushioning the volatility of the Peso despite massive foreign fund inflows.</p>
        <p><b>10. Philippine Stock Exchange (PSE) and Securities and Exchange Commission (SEC).</b>&nbsp;Through their supervision of listed companies and trading participants, both regulators have played an important role in promoting transparency and accountability in the local stock market. They established the platform that is necessary to handle bigger transaction volumes while instituting policies that ensure a level playing field for both local and foreign investors.</p>
        <p><b>11. Overseas Filipino Workers (OFWs).</b>&nbsp;It has been repeatedly said that OFWs are unsung heroes of our country. It is estimated that about 10M Filipinos are OFWs. Moreover, OFW remittances are expected to exceed $20.0B for 2012, amounting to ~8.6% of the country’s GDP. Their sacrifices and professional expertise have not only given their families a better future but have also contributed to robust domestic consumer demand and the resilience of our economy.</p>
        <p><b>12. Business Process Outsourcing (BPO) employees.</b>&nbsp;Like OFW remittances, BPO revenues also make a significant contribution to our economy. BPO Revenues are expected to reach $13.6B for this year, amounting to ~5.9% of GDP. It is estimated that close to 800k Filipinos are BPO employees. The country has become an attractive location for BPO companies because of the unique Filipino personality. Our labor force is young, trainable, diligent, helpful, courteous, amiable and fluent in English.</p>
        <p><b>13. Government Financial Institutions (GFIs).</b>&nbsp;Local GFIs such as GSIS, SSS and Landbank have been active participants in the local stock market. In a previous article, we cited the brilliant move of GSIS President Bernie Vergara to repatriate the foreign investments of GSIS and invest these locally (<i>Bad News, Good News,</i> August 15, 2011). The continued strong participation of local GFIs has not only kept our stock market buoyant but has also proven to be profitable for their benefactors.</p>
        <p><b>14. Mutual Funds, UITFs and Stockbrokers.</b>&nbsp;Mutual funds and UITFs play an important role in encouraging the participation of small investors in the local stock market. As investment vehicles, mutual funds and UITFs offer small investors access to diversified portfolios handled by professional fund managers (<i>All About Mutual Funds,</i> November 12, 2012). Local stockbrokers, on the other hand, provide sound financial advice and stock recommendations to their retail and institutional clients.</p>
        <p><b>15. Investors.</b>&nbsp;Local investors have been a constant presence in the market. We believe that the confidence conferred by foreign investors to our stock market emanates from local investors. Moreover, local investors have remained steadfast in their conviction about the country’s growth story and the resilience of our stock market. We would also like to thank the 5,641 investors of the Philequity Fund. We are happy to say that because of the continued trust and support of our investors, the Philequity Fund has delivered a YTD return of 33.5%. Moreover, Philequity now manages more than P7.0B in assets.</p>

        <p align="center"><b>Resilience of Markets</b></p>
        <p>Despite the volatility caused by macroeconomic headwinds such as the US fiscal cliff, the European sovereign debt crisis, the threat of a China hard landing and slowing global growth, global stock markets have not fallen. In fact, global stock indices have performed quite strongly for 2012. On the global front, we thank our Santa Claus, Ben Bernanke, and the other global central banks, because their actions continue to lift global stock markets while stimulating global economic growth. This has also translated to a stronger PSE Index which only experienced relatively shallow corrections despite its steep ascent. On the local front, the leadership of PNoy and his Cabinet, as well as strong domestic consumption, continue to keep our GDP growth buoyant and our local economy insulated from external shocks.</p>

        <p>As we have repeatedly said before, we believe that the fundamentals of the country are solid and that the Philippine stock market will continue to be resilient. Though corrections will always be there, we view these as buying opportunities because the bull market, which started in March 2009, is intact and strong. Since today is Christmas Eve, we would like to ask everyone to reflect on the blessings that we have received for this year and welcome 2013 with anticipation and hope. Merry Christmas!</p>

        	<p><i>For further stock market research and to view our previous articles, please visit our online trading platform at <a href="http://www.wealthsec.com">www.wealthsec.com</a> or call 634-5038. Our archived articles can also be viewed at <a href="http://www.philequity.net">www.philequity.net</a>.</i></p>

    	    </div>
</head>
<body>

</body>
</html>